project:
  machine_name: bolt
  prefix: BOLT
  human_name: 'BOLTed 8'
  profile:
    name: lightning
  local:
    protocol: https
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    - boltd8@svn-5767.devcloud.hosting.acquia.com:boltd8.git
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
